"""Globally keys and values"""

KEY_FEATURES = 'FEATURES'
KEY_LABEL = 'LABEL'

# Dataset
KEY_TRAINING = "TRAINING"
KEY_VALIDATION = "VALIDATION"
KEY_TEST = "TEST"

# Callback
KEY_TRAIN_LOSS = "TRAIN_LOSS"
KEY_TRAIN_METRIC = "TRAIN_METRIC"
KEY_VALIDATION_LOSS = "VALIDATION_LOSS"
KEY_VALIDATION_METRIC = "VALIDATION_METRIC"

# Evaluation
KEY_TRAINING_METRIC_EVAL = "TRAINING_METRICS"
KEY_VALIDATION_METRIC_EVAL = "VALIDATION_METRICS"

KEY_PCC = "PEARSON_CORRELATION_COEFFICIENT"
KEY_MSE = "MEAN_SQUARED_ERROR"
KEY_MAE = "MEAN_ABSOLUTE_ERROR"
KEY_R_SQUARE = "R2"

# Prediciton
KEY_PREDICT_TRAIN_Y = "PRED_TRAIN_Y"
KEY_PREDICT_VALID_Y = "PRED_VALID_Y"
KEY_PREDICT_TEST_Y = "PRED_TEST_Y"
KEY_TRUE_TRAIN_Y = "TRUE_TRAIN_Y"
KEY_TRUE_VALID_Y = "TRUE_VALID_Y"

# Saliency
KEY_SALIENCY_MAP = "SALIENCY_MAP"

# URL
KEY_URL = "KEY_URL"
KEY_MODEL_PLOT_URL = "MODEL_PLOT_URL"

# localstorage_id
KEY_COMMON_LOCALSTORAGE_ID = "COMMON_LOCALSTORAGE_ID"